### ISSUE TITLE
Incorrect initial momenta for plane wave problem.

### ISSUE THREAD

**Issue by pierfied** [pierfied/stupid#2]
https://github.com/pierfied/stupid/blob/47036014bb927a5addaf691d0afe5cc7e5b30134/test/test_problems.cpp#L43

I think there are three issues:
1. a0 should be squared since p = av = a^2 (dx/dt).
2. lgf should be the time derivative of lgf.
3. The final closing parenthesis is misplaced.

**Comment by rafaelgm9** [comment]
Fixed.
